### ISSUE TITLE
Only motion is working

### ISSUE THREAD

**Issue by domoticauser** [j-b-n/domoticz_reolink#4]
Only the motion is working, the 2 others not?
On the domoticz forum i see a user with the same issue.

**Comment by j-b-n** [comment]
This should fixed since commit 7587c2f.

**Comment by domoticauser** [comment]
Thanks! I will test it for a few days.

**Comment by j-b-n** [comment]
Good, it also works for Rik60 (https://www.domoticz.com/forum/viewtopic.php?p=314165#p314165)
